version: '3.8'

services:
  authentication:
    image: authentication
    container_name: authentication_container
    ports:
      - "5000:3000"
      
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sanvisal2302
      POSTGRES_DB: User
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "7000:7000"
    networks:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: kc_myadmin
      KEYCLOAK_ADMIN_PASSWORD: user@pass
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/mydatabase
      KC_DB_USERNAME: user_sample
      KC_DB_PASSWORD: user@pass
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres
    networks:
      - keycloak

volumes:
  postgres-data:
    driver: local

networks:
  keycloak:
    driver: bridge