version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user_sample
      POSTGRES_PASSWORD: user@pass
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - crud_sample

volumes:
  postgres-data:
    driver: local

networks:
  crud_sample:
    driver: bridge